'backend: Scripting':
- *.js
- *.json
- *.sh
- *.xml
- Dockerfile
- Gemfile
- Gemfile.lock
- all: ["!.vscode/**/*", "!.github/**/*"]

'backend: Styling':
- docs/**/*.css
- docs/_includes/*
- docs/_layouts/*
- docs/_tooltips/*
- docs/_data/*
- docs/_fonts/*
- docs/
  
'backend: Meta':
- .github/**/*
- .vscode/**/*
- docs/licenses
- ./LICENSE
- ./README.md
- ./.gitignore

'backend: Tags Modified':
- docs/pages/tags/*
- docs/_data/tags.yml

'wiki: Lighting':
- docs/pages/Lighting/**/*.md 
- docs/pages/Lighting/**/*.html
- docs/_data/sidebars/Lighting_sidebar.yml

'wiki: Sound':
- docs/pages/Sound/**/*.md
- docs/pages/Sound/**/*.html
- docs/_data/sidebars/Sound_sidebar.yml

'wiki: Overview':
- docs/pages/Overview/**/*.md
- docs/pages/Overview/**/*.html
- docs/*.md
- docs/_data/sidebars/Overview_sidebar.yml

'wiki: Images Modified':
- docs/images/**/*

'wiki: Posts':
- docs/_posts/**/*.md
- docs/_posts/**/*.html
