"wiki: Backend":
- any: ["docs/**/*.css"]
- docs/_includes/*
- docs/_layouts/*
- docs/_tooltips/*

"wiki: Lighting":
- any: ["docs/pages/Lighting/*.md", "docs/pages/Lighting/*.html"]
- docs/_data/sidebars/Lighting_sidebar.yml

"wiki: Sound":
- any: ["docs/pages/Sound/*.md", "docs/pages/Sound/*.html"]
- docs/_data/sidebars/Lighting_sidebar.yml

"wiki: Main":
- any: ["docs/pages/Wiki/*.md", "docs/pages/Wiki/*.html"]
- docs/_data/sidebars/wiki_sidebar.yml