'backend: Scripting':
- docs/_scripts/*
- vscode/*
- docs/js/*.js
- docs/pdf/*
- docs/pdfconfigs/*
- docs/var/*
- ./* #Yes this will cause problems with index.md and 404.md but I can't do anything about that right now
- docs/*

'backend: Styling':
- docs/**/*.css
- docs/_includes/*
- docs/_layouts/*
- docs/_tooltips/*
- docs/_data/*
- docs/_fonts/*
- docs/
  
'backend: Meta':
- .github/*
- docs/licenses
- ./LICENSE
- ./README.md
- ./.gitignore


'wiki: Lighting':
- docs/pages/Lighting/*.md 
- docs/pages/Lighting/*.html
- docs/_data/sidebars/Lighting_sidebar.yml

'wiki: Sound':
- docs/pages/Sound/*.md
- docs/pages/Sound/*.html
- docs/_data/sidebars/Lighting_sidebar.yml

'wiki: Main':
- docs/pages/Wiki/*.md
- docs/pages/Wiki/*.html
- docs/*.md
- docs/_data/sidebars/Overview_sidebar.yml

'wiki: Images Modified':
- docs/images/*