blank_issues_enabled: false
contact_links:
  - name: Get in touch
    url: mailto:techwiki@b-macdonald.ca
    about: If you are looking to get in touch about anything regarding the wiki, use this link to send an email.
