destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/wiki-pdf"
port: 4010
output: pdf
product: wiki
print_title: "EPS Tech Wiki — Main Overview"
#print_subtitle: version 6.0
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: false
      search: true

pdf_sidebar: Overview_sidebar
