destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/Lighting-pdf"
port: 4011
output: pdf
product: Lighting
print_title: Lighting Wiki
#print_subtitle: version 1.0
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: false
      search: true

pdf_sidebar: Lighting_sidebar
