destination: _site/
url: "http://127.0.0.1:4012"
baseurl: "/Sound-pdf"
port: 4012
output: pdf
product: Sound
print_title: Sound documentation
#print_subtitle: version 1.0
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: false
      search: true

pdf_sidebar: Sound_sidebar
