name: Jekyll Tester
on: [pull_request_target]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Test Jekyll
        uses: epstechtheatre/Jekyll-Tester@v1.1.0
        with:
          path: docs/

