name: CSpell Checker
on: [ pull_request ]

jobs:
  Spell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: zwaldowski/cspell-action@1.0.0

        with:
          paths: "./**/*.md"
          config: ./.vscode/cspell.json
          exclude: LICENSE.md